version: '3.9'
services:
  backend-fastapi:
    build: ./INF3995-Backend
    depends_on:
      - db
    network_mode: host
    volumes:
      - ./INF3995-Backend/app:/src/app
      - /app/ros_nodes/build
      - /app/ros_nodes/install
      - /app/ros_nodes/log
    image: fastapi
    container_name: backend-container
    environment:
      - ROS_DOMAIN_ID=62
      - TERM='xterm-256color'
      - SQLALCHEMY_DATABASE_HOST=localhost
      - DEPLOYMENT=DEV # or PROD
    command: /bin/bash -c "/start-app.sh"
  db:
    image: postgres:13
    ports:
      - "5430:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: inf3995    
      POSTGRES_USER: eq102
      POSTGRES_PASSWORD: root  
  frontend-angular:
    ports:
      - "4200:4200"
    build: ./INF3995-Frontend/client
    network_mode: host
    image: inf3995-frontend
    volumes:
      - ./INF3995-Frontend/client:/usr/src/app
    stdin_open: true
    tty: true
    container_name: frontend-angular
    command: /bin/bash -c "npm i && npm run docker-dev"
    depends_on:
      - backend-fastapi
volumes:
  postgres_data:
